###########################################################
#
#   iCloud3 Configuration Parameters
#
#   These parameters will override those specified in the HA
#   configuration.yaml file. They can be used to change the
#   iCloud3 operations without restarting HA. To do this,
#   change the parameter in this file and select 'Restart-iC3'
#   on the iCloud3 Event Log screen.
#
###########################################################

#--Track Devices Parameters-------------------------------------
#track_devices:
#  - gary_iphone > gary@email.com, gary.png
#  - lillian_iphone > lillian@email.com, lillian.png

#event_log_card_directory: 'www/custom_cards'

#--Zone/Tracking Parameters-----------------------------------------
#inzone_interval: '60 min'
#max_interval: '4 hrs'
#center_in_zone: True
#stationary_inzone_interval: '30 min'
#stationary_still_time: '8 min'
#stationary_zone_offset: 1, 0
#travel_time_factor: .6
#distance_method: waze

#--Accuracy Parameters-------------------------------------
#gps_accuracy_threshold: 100
#ignore_gps_accuracy_inzone: True
#old_location_threshold: '3 min'

#--Waze Parameters-----------------------------------------
#distance_method: waze
#waze_region: US
#waze_min_distance: 1
#waze_max_distance: 9999
#waze_realtime: False

#-- Other Parameters---------------------------------------
#display_text_as:
#  - gary-real-email@gmail.com > gary-email@email.com
#  - lillian-real-email@gmail.com > lillian-emailt@email.com
#unit_of_measurement: mi

#-- Debug/Logging Parameters---------------------------------------
#log_level: debug
#log_level: debug+intervalcalc
#log_level: debug+rawdata
